### ISSUE TITLE
Problem when picture is too big

### ISSUE THREAD

**Issue by szigya** [rizkyramadhan/yii-user-profilepic#11]
When picture is bigger than the div can be, cropping fails. E.g. I have a picture with the size 1024x768, but the div I use is just 600 px wide. I crop the picture and the preview of it is perfect. After I click on save, the saved thumbnail shows an other cropping.
I hope I could write it down clear enough, if not, tell me :). 
Thanks,
Mike

**Comment by rizkyramadhan** [comment]
Hi, sorry but I dont maintain this extension anymore.

You should look into another extension.

**Comment by szigya** [comment]
Ok. Anyway, I found out that the maxWidth and maxHeight parameters are not working as a treshold (so I can upload a picture even if I set these to 1), but if I write the maximum size of the container div, everything works fine. Of course it doesn't solve the problem if one uses a responsive design, but can be a workaround for others.

**Comment by rizkyramadhan** [comment]
Great, you can make pull request if you want, so I can merge your solution
into this repo.

**Comment by szigya** [comment]
Just for the record, it doesn't need to change the code, it's just about using the parameters for another purpose.
